haproxy_consul_template: /usr/local/bin/consul-template -consul=gliderlabs_consul:8500 -template /app/haproxy.cfg.ctmpl:/etc/haproxy/haproxy.cfg:/app/reload_haproxy.sh
haproxy: sleep 3 ; /usr/sbin/haproxy -V -db -f /etc/haproxy/haproxy.cfg
