haproxy_consul_template: /usr/local/bin/consul-template -consul=consul:8500 -template /app/haproxy.cfg.ctmpl:/etc/haproxy/haproxy.cfg
haproxy: sleep 5 ; /usr/sbin/haproxy -V -db -f /etc/haproxy/haproxy.cfg
