---
stacks:
  - name: service-router
    description: Service Router for home
    units:
      - name: haproxy
        version: 1.0.0
        dockerfile: ./haproxy/Dockerfile
        ports:
          - "80:80/tcp"
          - "443:443/tcp"
          - "1234:1234/tcp"
        volumes:
          - /data/service-router/logs:/var/log
