#!/bin/bash

cat << EOS | sudo tee /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.1.1.254
nameserver 8.8.8.8
nameserver 8.8.4.4
search local
EOS

DOCKER_DEBUG=true bundle exec percheron recreate gliderlabs
DOCKER_DEBUG=true bundle exec percheron recreate home
